config/routes.rb
Rails.application.routes.draw do
  resources :boards do
    collection do
      post 'import'
    end

    resources :lists, only: [:new, :create], shallow: true do
      resources :cards, only: :create
    end
  end

  resource :user, only: [:edit, :update]

  devise_for :users

  root 'boards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  validates :name, presence: true
  validates :visibility, inclusion: { in: %w(public private) }

  belongs_to :user
  has_many :lists, dependent: :destroy
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list

  validates :title, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :cards, dependent: :destroy

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :boards, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = current_user.boards
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @lists = @board.lists
  end

  # GET /boards/new
  def new
    @board = Board.new

    begin
      importer = TrelloBoardsImporter.init_for_user(current_user)
      @trello_boards = importer.boards
    rescue Trello::Error
      @trello_importer_error = true
    end
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = current_user.boards.build(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    importer = TrelloBoardsImporter.init_for_user(current_user)
    @board = importer.import(trello_board_id_param)

    current_user.boards << @board

    @board.save!

    redirect_to @board, notice: 'Board was successfully updated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name, :visibility, :favorite)
    end

    def trello_board_id_param
      params.require(:trello_board_id)
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_list

  def create
    @card = @list.cards.build(card_params)

    if @card.save
      redirect_to @list.board
    else
      head :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def card_params
    params.require(:card).permit(:title)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_board

  def new
    @list = List.new
  end

  def create
    @list = @board.lists.build(list_params)

    if @list.save
      redirect_to @board
    else
      render :new
    end
  end

  private

  def set_board
    @board = Board.find(params[:board_id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: 'User configuration were successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:developer_public_key, :member_token)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
  def visibility_options
    [
      ['Public', 'public'],
      ['Private', 'private']
    ]
  end

  def trello_boards_options(trello_boards)
    trello_boards.map { |b| [b.name, b.id] }
  end
end

app/views/boards/_board.html.erb
<div class="col-xs-12 col-sm-3">
  <div class="panel panel-default">
    <%= link_to board do %>
      <div class="panel-body">
        <h3 class="panel-title"><%= board.name %></h3>
      </div>
    <% end %>
  </div>
</div>

app/views/boards/_form.html.erb
<%= form_with(model: board, local: true) do |form| %>
  <% if board.errors.any? %>
    <div class="alert alert-danger">
      <strong>Error:</strong> <%= board.errors.full_messages.to_sentence %>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :board_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :visibility %>
    <%= form.select :visibility, visibility_options, {}, id: :board_visibility, class: "form-control" %>
  </div>

  <div class="checkbox">
    <%= form.label :favorite do %>
      <%= form.check_box :favorite, id: :board_favorite %> Favorite
    <% end %>
  </div>

  <%= form.submit class: "btn btn-default" %>
  <%= link_to 'Back', boards_path %>
<% end %>

app/views/boards/_import_form.html.erb
<%= form_with(url: import_boards_path(board)) do |f| %>
  <div class="form-group">
    <%= f.label "Trello Board ID", for: "trello_board_id" %>
    <%= f.select :trello_board_id, trello_boards_options(trello_boards), {}, class: "form-control", id: "trello_board_id" %>
  </div>

  <%= f.submit 'Import', class: "btn btn-default" %>
<% end %>

app/views/boards/_list.html.erb
<div class="col-xs-12 col-sm-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h3 class="panel-title"><%= list.name %></h3>
    </div>

    <ul class="list-group">
      <% list.cards.each do |card| %>
        <li class="list-group-item"><%= card.title %></li>
      <% end %>
    </ul>

    <div class="panel-footer">
      <%= form_with(model: [list, Card.new]) do |f| %>
        <div class="form-group">
          <%= f.text_area :title, class: "form-control", placeholder: "Add a new card", required: true %>
        </div>
        <%= f.submit class: "btn btn-default btn-sm" %>
      <% end %>
    </div>
  </div>
</div>

app/views/boards/edit.html.erb
<div class="row">
  <div class="col-xs-4 col-xs-offset-4">
    <div class="page-header">
      <h1>Edit Board</h1>
    </div>
    <%= render 'form', board: @board %>
  </div>
</div>

app/views/boards/index.html.erb
<h1>Boards</h1>

<div class="row">
  <%= render @boards %>

  <div class="col-xs-12 col-sm-3">
    <div class="panel panel-default">
      <%= link_to new_board_path do %>
        <div class="panel-body">
          <h3 class="panel-title">Create new board...</h3>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/boards/new.html.erb
<div class="row">
  <div class="col-xs-4 col-xs-offset-4">
    <div class="page-header">
      <h1>New Board</h1>
    </div>
    <%= render 'form', board: @board %>
  </div>
</div>

<div class="row">
  <div class="col-xs-4 col-xs-offset-4">
    <div class="page-header">
      <h3>... or import a board from Trello</h3>
    </div>

    <% unless @trello_importer_error %>
      <%= render 'import_form', board: @board, trello_boards: @trello_boards %>
    <% else %>
      If you want to import boards from Trello, please provide your account keys in your
      <%= link_to "Account Settings page", edit_user_path %>
    <% end %>
  </div>
</div>

app/views/boards/show.html.erb
<h3><%= @board.name %>
  <span class="label label-info pull-right"><%= @board.visibility %></span>
</h3>

<hr/>

<div class="row">
  <%= render partial: 'list', collection: @lists %>

  <div class="col-xs-12 col-sm-3">
    <div class="panel panel-default">
      <%= link_to new_board_list_path(@board) do %>
        <div class="panel-body">
          <h3 class="panel-title">Create new list...</h3>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= link_to 'Back', boards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrelloApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>

    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12">
          <%= yield %>
        </div>
      </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: [board, list], local: true) do |f| %>
  <% if list.errors.any? %>
    <div class="alert alert-danger">
      <strong>Error:</strong> <%= list.errors.full_messages.to_sentence %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", id: "list_name" %>
  </div>

  <%= f.submit class: "btn btn-default" %>
  <%= link_to 'Back', board_path(board) %>
<% end %>

app/views/lists/new.html.erb
<div class="row">
  <div class="col-xs-4 col-xs-offset-4">
    <div class="page-header">
      <h1>New List for <span class="text-info"><%= @board.name %></span></h1>
    </div>
    <%= render 'form', list: @list, board: @board %>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Trello App', root_path, class: 'navbar-brand' %>
    </div>

    <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Settings', edit_user_path %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, method: :put) do |form| %>
  <% if user.errors.any? %>
    <div class="alert alert-danger">
      <strong>Error:</strong> <%= user.errors.full_messages.to_sentence %>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :developer_public_key %>
    <%= form.text_field :developer_public_key, id: :user_developer_public_key, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :member_token %>
    <%= form.text_field :member_token, id: :user_member_token, class: "form-control" %>
  </div>

  <%= form.submit 'Save', class: "btn btn-default" %>
  <%= link_to 'Back', boards_path %>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-xs-4 col-xs-offset-4">
    <div class="page-header">
      <h1>Edit User Preferences</h1>
    </div>
    <%= render 'form', user: @user %>
  </div>
</div>